config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :articles do
    resources :comments
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates :title, presence: true,
                      length: { minimum: 5 }
    belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end
    
    def new
        @article = current_user.articles.build
    end
       
    def edit
      @article = Article.find(params[:id])
    end
     
    def create
      @article = current_user.articles.build(article_params)
     
      if @article.save
        redirect_to @article
      else
        render 'new'
      end
    end

    def update
      @article = Article.find(params[:id])
     
      if @article.update(article_params)
        redirect_to @article
      else
        render 'edit'
      end
    end  

    def destroy
      @article = Article.find(params[:id])
      @article.destroy
      
      redirect_to articles_path
    end  
    
    private
      def article_params
        params.require(:article).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article)
    end
     
    private
        def comment_params
          params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
<div class="column is-three-fifths is-offset-one-fifth"> 
  <div class="content has-text-left">

  
  <% @articles.each do |article| %>
  <div>
  <%= article.user.email %>
  </div>
  <div>
    <h3 class="is-size-4"><strong>
      <%= article.title %>
    </strong></h3>
  </div>
  <div>
    <%= article.text %>
  </div> 
  <div> 
    <%= link_to 'Show', article_path(article) %> 
      <% if article.user == current_user %>
       | <%= link_to 'Edit', edit_article_path(article) %> 
       | <%= link_to 'Delete', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
      <% end %>
      <div><hr></div>
    <% end %>
    </div> 
  </div> 
</div>

app/views/articles/_form.html.erb
<div class="container is-fullhd">
  <div class="notification has-background-white">
  <div class="column is-three-fifths is-offset-one-fifth"> 
    <div class="box">
  <%= form_with model: @article, local: true do |form| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  </div>
<% end %>
 <% if user_signed_in? %>
  <div class="field">
    <!--<%= form.label :title %><br>-->
    <%= form.text_field :title, class: 'input', placeholder: 'Title' %>
  </div>
 
  <div class="field">
    <%= form.text_area :text, class: 'input', placeholder: 'Text' %>
  </div>
 
  <div class="actions">
    <%= form.submit  "Submit Article", class: "button is-dark is-medium"  %>
  </div>
            
 <% end %>
<% end %>
</div>
</div>
</div>
</div>

app/views/articles/edit.html.erb
<div class="coloumn has-text-centered">
    <h1 class="title is-3 has-text-dark">Edit article</h1>
    <%= render 'form' %>
    <%= link_to 'Back', articles_path %>   
</div>

app/views/articles/index.html.erb
<!--  This container is <strong>fullwidth</strong> <em>until</em> the <code>$fullhd</code> breakpoint. -->
<div class="container is-fullhd ">
  <div class="coloumn has-text-centered ">
    <div class="notification has-background-white">

<!-- article content starts here -->
<h2 class="title is-3 ">Blog Articles</h2>
<% if user_signed_in? %>
<%= link_to 'New article', new_article_path, class: "button is-dark is-medium" %>
<% end %>

<%= render 'article' %>

<%= form_with scope: :article, url: articles_path, local: true do |form| %>
<% end %>
</div>
</div>
</div>
</div>


<!-- article content ends here -->
<!-- This container ends here <strong>fullwidth</strong> <em>until</em> the <code>$fullhd</code> breakpoint. -->

app/views/articles/new.html.erb
<div class="coloumn has-text-centered">
    <h1 class="title is-3 has-text-dark">New article</h1>
    <%= render 'form' %>
    <%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<!--  This container is <strong>fullwidth</strong> <em>until</em> the <code>$fullhd</code> breakpoint. -->
<div class="container is-fullhd ">
  <div class="notification has-background-white">
    <p>
      <strong>Title:</strong>
      <%= @article.title %>
    </p>
    <p>
      <strong>Text:</strong>
      <%= @article.text %>
    </p>
        <div class="columns is-mobile is-centered">
          <div class="column is-half">
            <h4 class="is-size-4"><strong>Comments</strong></h4>
          </div>
        </div>
        <div class="columns is-mobile is-centered">
          <div class="column is-half">
            <%= render @article.comments %>
          </div>
        </div>
        <div class="columns is-mobile is-centered">
          <div class="column is-half">
        <h2>Add a comment:</h2>
          <%= render 'comments/form' %>
          <%= link_to 'Edit', edit_article_path(@article) %> |
          <%= link_to 'Back', articles_path %> 
        </div>
        </div>  
    </div>
</div>
<!--  End of Show article content only -->

<!-- This container ends here <strong>fullwidth</strong> <em>until</em> the <code>$fullhd</code> breakpoint. -->
  

app/views/comments/_comment.html.erb
<div class="column"> 
  <div class="content has-text-left">
  <div>

  <%= @article.user.email %>
</div> 
<!--<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>-->
<p>
  <strong>Writes:</strong>
  <%= comment.body %>
</p>
<p>
<% if @article.user == current_user %>
  <%= link_to 'Destroy Comment', [comment.article, comment],
          method: :delete,
          data: { confirm: 'Are you sure?' } %>
<% end %>
</p>

</div> 

</div> 
<div><hr></div>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <!--
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  -->
  <div class="field">
    <!--<%= form.label :body %><br> -->
    <%= form.text_area :body, placeholder: 'Add a comment', class: 'input'  %>
  </div>
<div class="actions">
  <%= form.submit "Submit", class: "button is-dark is-medium" %>
</div>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_alerts.html.erb
<!--
<div>
    <div class="content has-text-centered has-background-warning">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
    </div>
</div>
-->

app/views/layouts/_nav.html.erb
<nav class="navbar is-warning" role="navigation" aria-label="main navigation">
        <div class="navbar-brand"><span style="margin:.25rem 0rem 0rem 2rem">
          <%= link_to 'Mariens Page', welcome_index_path, class: "title" %>   
            </span>
              <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
              </a>
        </div>
        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start">
            <%= link_to 'Home', welcome_index_path, class: "navbar-item" %>
            <%= link_to 'Blog', articles_path, class: "navbar-item" %>
            <%= link_to 'Reservation', welcome_index_path, class: "navbar-item" %>
            <%= link_to 'Contact',welcome_index_path, class: "navbar-item" %>
          </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
        <% if user_signed_in? %>
        <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "button is-dark" %>
        <% else %>
         <strong><span style="margin-right:0.5rem">
          <%= link_to 'Sign up', new_user_registration_path, class: "button is-dark" %>
         </span></strong>
         <strong><span style="margin-right:1rem">
          <%= link_to 'Log in', new_user_session_path, class: "button is-dark" %>
          </span></strong>
        <% end %>  
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mariam</title>
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/alerts' %>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<section class="hero is-dark is-medium">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title is-centered">
        Welcome to Marien's Page
      </h1>
      <h2 class="subtitle">
        Where all things beauty is made convenient
      </h2>
    </div>
  </div>
</section>